services:
  python:
    build:
      context: .
      dockerfile: ../docker/python/Dockerfile
    container_name: python
    command: /bin/sh
    volumes:
      - type: bind
        source: .
        target: /sample-google-custom-search-api
    environment:
      GOOGLE_API_KEY: ""
      CUSTOM_SEARCH_ENGINE_ID: ""
    tty: true
    stdin_open: true
